#!/bin/bash

touch state.yaml

docker run --rm -it \
    --name eve-posbot \
    --volume "$(pwd)"/test-config.yaml:/app/foo.yaml:ro \
    --volume "$(pwd)"/test-state.yaml:/app/state.yaml \
    boravyvorant/eve-posbot foo.yaml
